var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 19.66, text: "Risalah terikatnya" },
  { time: 24.07, text: "Batin dan raga yang mengunci" },
  { time: 28.77, text: "Diatas sang maha daya" },
  { time: 32.64, text: "Semua kendali terambil alih" },
  { time: 38.16, text: "Jikalau kau keluhkan" },
  { time: 42.99, text: "Dengung sumbang yang mengganggu" },
  { time: 47.77, text: "Buka lagi visimu" },
  { time: 51.68, text: "Kau tahu mana urutan satu" },
  { time: 58.85, text: "Diantara pusaran nirfungsi" },
  { time: 66.02, text: "Petakan semua lagi" },
  { time: 70.83, text: "Titik tuju yang tlah terpatri" },
  { time: 77.26, text: "Melamban bukanlah hal yang tabu" },
  { time: 85.21, text: "Kadang itu yang kau butuh" },
  { time: 89.85, text: "Bersandar hibahkan bebanmu" },
  { time: 95.38, text: "Rotasikan pandanganmu" },
  { time: 99.95, text: "Ambil sudut yang terbaru" },
  { time: 104.57, text: "Belum pernah kau coba" },
  { time: 108.45, text: "Lihat semua bukan dari matamu" },
  { time: 114.03, text: "Kelak kau kan mengingat" },
  { time: 119.25, text: "Yang membawamu kesini" },
  { time: 123.53, text: "Kami pernah disitu" },
  { time: 127.07, text: "Di posisimu" },
  { time: 129.84, text: "Helakan kesahmu" },
  { time: 139.34, text: "Diantara pusaran nirfungsi" },
  { time: 146.66, text: "Petakan semua lagi" },
  { time: 151.05, text: "Titik tuju yang tlah terpatri" },
  { time: 158.02, text: "Melamban bukanlah hal yang tabu" },
  { time: 165.73, text: "Kadang itu yang kau butuh" },
  { time: 170.21, text: "Bersandar hibahkan bebanmu" },
  { time: 176.85, text: "Tak perlu kau berhenti kurasi" },
  { time: 184.42, text: "Ini hanya sementara" },
  { time: 189.18, text: "Bukan ujung dari rencana" },
  { time: 195.87, text: "Jalanmu kan sepanjang niatmu" },
  { time: 203.47, text: "Simpan tegar dalam hati" },
  { time: 208.21, text: "Dua sembilan kau terus mencari" },
  { time: 217.51, text: "Ho oh" },
  { time: 250.86, text: "Sebutlah namaNya" },
  { time: 255.67, text: "Tetap di jalanNya" },
  { time: 260.08, text: "Kelak kau mengingat" },
  { time: 264.76, text: "Kau akan teringat" },
  { time: 269.75, text: "Sebutlah namaNya" },
  { time: 274.57, text: "Tetap di jalanNya" },
  { time: 278.97, text: "Kelak kau mengingat" },
  { time: 283.75, text: "Kau akan teringat" },
  { time: 288.76, text: "Sebutlah namaNya" },
  { time: 293.28, text: "Tetap di jalanNya" },
  { time: 297.90, text: "Kelak kau mengingat" },
  { time: 302.74, text: "Kau akan teringat" },
  { time: 307.64, text: "Sebutkanlah namaNya" },
  { time: 312.74, text: "Resapilah jalanNya" },
  { time: 314.80, text: "Kelak kau mengingat" },
  { time: 321.76, text: "Kau akan teringat" },
  { time: 347.91, text: "Terus berenang" },
  { time: 352.47, text: "Lanjutlah mendaki" },
  { time: 366.85, text: "Terus berenang" },
  { time: 371.84, text: "Lanjutlah mendaki" },
  { time: 385.65, text: "Terus berenang" },
  { time: 390.49, text: "Lanjutlah mendaki" },
  { time: 404.71, text: "Terus berenang" },
  { time: 409.43, text: "Lanjutlah mendaki" }
];