var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 41.15, text: "Ditekan dari segala sisi" },
  { time: 46.75, text: "Sering kali hilang arti" },
  { time: 50.20, text: "Aku hidup untuk siapa?" },
  { time: 54.74, text: "Ku sudah tidak nyaman lagi" },
  { time: 60.91, text: "Bermimpi pun tahu diri" },
  { time: 63.80, text: "Apa sebaiknya pergi?" },
  { time: 69.28, text: "Jika semua bersandar padaku" },
  { time: 75.97, text: "Lalu aku bersandar ke mana?" },
  { time: 84.98, text: "Mengalah walau bukan aku yang salah" },
  { time: 91.61, text: "Membisu saat semua sibuk beradu" },
  { time: 98.92, text: "Walau tak rela pun kubantu, berdoa ini semua" },
  { time: 105.47, text: "Berakhir di aku" },
  { time: 123.16, text: "Setiap hari ku mengais" },
  { time: 129.01, text: "Harta yang tak kumiliki" },
  { time: 132.54, text: "Apa yang aku miliki?" },
  { time: 137.72, text: "Jika semua bersandar padaku" },
  { time: 144.47, text: "Lalu aku bersandar ke mana?" },
  { time: 149.88, text: "Mengalah walau bukan aku yang salah" },
  { time: 156.78, text: "Membisu saat semua sibuk beradu" },
  { time: 163.99, text: "Walau tak rela pun kubantu, berdoa ini semua" },
  { time: 170.65, text: "Berakhir di aku" },
  { time: 177.28, text: "Berakhir di aku" },
  { time: 180.49, text: "Berakhir di aku (berakhir di aku)" },
  { time: 190.90, text: "Berakhir di aku" },
  { time: 194.42, text: "Berakhir di aku" },
  { time: 201.78, text: "Walau tak rela pun kubantu, berdoa ini semua" },
  { time: 208.69, text: "Berakhir di aku" },
  { time: 218.64, text: "Membisu saat semua sibuk beradu (sibuk beradu)" },
  { time: 226.17, text: "Walau tak rela pun kubantu, berdoa ini semua" },
  { time: 232.45, text: "Berakhir" },
  { time: 239.43, text: "Berakhir di aku" },
  { time: 247.61, text: "berakhir di aku" },
  { time: 249.83, text: "(Berakhir di aku) hu-hu, uh-hu, uh-hu" }
];