var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 20.85, text: "Bun, hidup berjalan seperti bajingan" },
  { time: 31.18, text: "Seperti landak yang tak punya teman" },
  { time: 41.78, text: "Ia menggonggong bak suara hujan" },
  { time: 51.88, text: "Dan kau pangeranku mengambil peran" },
  { time: 63.52, text: "Bun, kalau saat hancur, ku disayang" },
  { time: 73.89, text: "Apalagi saat ku jadi juara" },
  { time: 84.57, text: "Saat tak tahu arah, kau di sana" },
  { time: 95.26, text: "Menjadi gagah saat ku tak bisa" },
  { time: 105.50, text: "Sedikit kujelaskan tentangku dan kamu" },
  { time: 111.07, text: "Agar seisi dunia tahu" },
  { time: 116.49, text: "Keras kepalaku sama denganmu" },
  { time: 121.62, text: "Caraku marah, caraku tersenyum" },
  { time: 127.15, text: "Seperti detak jantung yang bertaut" },
  { time: 132.47, text: "Nyawaku nyala kar'na denganmu" },
  { time: 137.84, text: "Aku masih ada sampai di sini" },
  { time: 142.92, text: "Melihatmu kuat setengah mati" },
  { time: 148.25, text: "Seperti detak jantung yang bertaut" },
  { time: 153.65, text: "Nyawaku nyala kar'na denganmu" },
  { time: 170.26, text: "Bun, aku masih tak mengerti banyak hal" },
  { time: 180.42, text: "Semuanya berenang di kepala" },
  { time: 191.21, text: "Dan kau, dan semua yang kau tahu tentangnya" },
  { time: 201.97, text: "Menjadi jawab saat ku bertanya" },
  { time: 212.22, text: "Sedikit kujelaskan tentangku dan kamu" },
  { time: 217.63, text: "Agar seisi dunia tahu" },
  { time: 223.08, text: "Keras kepalaku sama denganmu" },
  { time: 228.17, text: "Caraku marah, caraku tersenyum" },
  { time: 233.66, text: "Seperti detak jantung yang bertaut" },
  { time: 239.05, text: "Nyawaku nyala kar'na denganmu" },
  { time: 244.54, text: "Aku masih ada sampai di sini" },
  { time: 249.78, text: "Melihatmu kuat setengah mati" },
  { time: 255.14, text: "Seperti detak jantung yang bertaut" },
  { time: 260.40, text: "Nyawaku nyala kar'na denganmu" },
  { time: 265.84, text: "Semoga lama hidupmu di sini" },
  { time: 271.04, text: "Melihatku berjuang sampai akhir" },
  { time: 276.45, text: "Seperti detak jantung yang bertaut" },
  { time: 281.67, text: "Nyawaku nyala kar'na denganmu" },
  { time: 287.77, text: "Hu-oh-oh, hu-uh-ho, hu-oh" }
];