var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 18.61, text: "Hai perkenalkan aku jiwa yang bertahan" },
  { time: 23.93, text: "Sudah ditempa keras oleh banyak cerita" },
  { time: 29.62, text: "Mati berkali-kali tapi bisa hidup lagi" },
  { time: 35.18, text: "Konon jika selamat aku semakin hebat" },
  { time: 43.07, text: "Daur hidup akan selalu berputar" },
  { time: 48.54, text: "Tugasku hanya bertahan" },
  { time: 51.87, text: "Terus jalan dan mengalirlah seperti air" },
  { time: 57.36, text: "Dari lahir sampai ku jadi debu di akhir" },
  { time: 65.54, text: "Bohong jika aku bilang selalu kuat" },
  { time: 70.91, text: "Lemah datang di saat-saat tak tepat" },
  { time: 76.52, text: "Beruntung aku dijaga kawan erat" },
  { time: 81.80, text: "Ayat buat ku dan dia semakin dekat" },
  { time: 87.47, text: "Daur hidup akan selalu berputar" },
  { time: 93.02, text: "Tugasku hanya bertahan" },
  { time: 96.59, text: "Terus jalan dan mengalirlah seperti air" },
  { time: 102.13, text: "Dari lahir sampai ku jadi debu di akhir" },
  { time: 132.54, text: "Daur hidup akan selalu berputar" },
  { time: 137.62, text: "Tugasku hanya bertahan" },
  { time: 141.08, text: "Terus jalan dan mengalirlah seperti air" },
  { time: 146.53, text: "Dari lahir sampai ku jadi debu di akhir" },
  { time: 152.62, text: "Hai semua tangis dan tawa di depan mata" },
  { time: 158.10, text: "Aku tak pilih kasih kan ku peluk semua" }
];