var lyrics = [
  { time: 0.00, text: "Ku tak pernah ikat rambutku lagi semenjak kaubilang" },
  { time: 5.33, text: "Rambutku indah bila terurai panjang" },
  { time: 11.69, text: "Baju hitamku tak pernah kusentuh lagi sejak hari itu" },
  { time: 17.95, text: 'Kaubilang, "Warna gelap membosankan"' },
  { time: 23.63, text: "Kubaca sampai tuntas semua buku yang paling kausuka" },
  { time: 29.39, text: "Mungkin suatu saat kauanggapku cerdas" },
  { time: 35.32, text: 'Tak kuhiraukan kata mereka, "Ini berlebihan"' },
  { time: 41.62, text: "Untukmu, apa pun akan kulakukan" },
  { time: 48.04, text: "Ingin sempurna di matamu" },
  { time: 54.22, text: "Hanya itu yang aku mau" },
  { time: 60.18, text: "Namun, tampaknya sempurna tak cukup" },
  { time: 65.80, text: "Bagimu, hm-mm" },
  { time: 74.61, text: "11.000 kilometer kutempuh sendirian" },
  { time: 80.51, text: "Bawa pelukku yang ternyata tak kaurindukan" },
  { time: 86.50, text: "36.000 kaki di atas laut kutahan" },
  { time: 92.29, text: "Kau tahu benar ku takut ketinggian" },
  { time: 98.96, text: "Ingin sempurna di matamu" },
  { time: 105.15, text: "Hanya itu yang aku mau" },
  { time: 111.03, text: "Namun, tampaknya sempurna tak cukup" },
  { time: 116.90, text: "Bila ternyata aku bukan yang kauperlu" },
  { time: 123.38, text: "Kubatalkan setiap janji" },
  { time: 128.79, text: "Hanya kar'na takut tiba-tiba kau butuh aku di sisimu" },
  { time: 138.07, text: "Ingin sempurna di matamu" },
  { time: 144.00, text: "Hanya itu yang aku mau" },
  { time: 150.18, text: "Namun, tampaknya sempurna tak cukup" },
  { time: 155.96, text: "Bagimu, hu-uh" },
  { time: 162.01, text: "Ingin sempurna di matamu" },
  { time: 168.05, text: "Ingin kaulihat aku lebih jauh" },
  { time: 174.05, text: "Ingin kautahu" },
  { time: 179.80, text: "Tiada yang sayangimu lebih dari aku" }
];