var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 13.68, text: "Dari dulu kulebih-lebihkan semua" },
  { time: 19.95, text: "Padahal yang kaulakukan tak seberapa" },
  { time: 26.30, text: "Agar seisi dunia tahu" },
  { time: 29.53, text: "Dan anggapku paling beruntung" },
  { time: 34.73, text: "Milikimu" },
  { time: 52.18, text: "Kukarang cerita yang semula tak ada" },
  { time: 58.28, text: "Caraku sampaikan seolah semua nyata" },
  { time: 64.62, text: "Agar semuanya setuju" },
  { time: 67.88, text: "Dan yakin pada pilihanku" },
  { time: 72.93, text: "Memilihmu" },
  { time: 76.89, text: "Sifat baikmu yang orang tahu" },
  { time: 81.60, text: "Itu karanganku" },
  { time: 89.32, text: "Sifat aslimu yang hancurkanku" },
  { time: 94.33, text: "Mereka tak tahu" },
  { time: 102.16, text: "Dan bahkan setelah semua" },
  { time: 105.35, text: "Yang kaulakukan padaku" },
  { time: 108.77, text: "Ku tetap bela kamu" },
  { time: 111.92, text: "Di depan teman-temanku" },
  { time: 114.74, text: "Dan mungkin saja bisa jadi" },
  { time: 118.32, text: "Bila kamu datang lagi" },
  { time: 121.57, text: "Ku 'kan terimamu kembali" },
  { time: 131.51, text: "Hu-uh-uh-uh, hu-uh" },
  { time: 138.23, text: "Kudengar kamu sibuk ke sana-kemari" },
  { time: 144.56, text: "Bersihkan namamu di mata orang lain" },
  { time: 151.02, text: "Kau cerita dari sisimu" },
  { time: 154.41, text: "Kaubilang tak semua salahmu" },
  { time: 157.70, text: "Berharap ada yang memihakmu" },
  { time: 163.28, text: "Sifat baikmu yang orang tahu" },
  { time: 167.73, text: "Itu karanganku" },
  { time: 175.89, text: "Sifat aslimu yang hancurkanku" },
  { time: 180.64, text: "Kini m'reka tahu" },
  { time: 188.55, text: "Dan bahkan setelah semua" },
  { time: 192.13, text: "Yang kaulakukan padaku" },
  { time: 195.16, text: "Ku tetap bela kamu" },
  { time: 198.25, text: "Di depan teman-temanku" },
  { time: 201.10, text: "Dan mungkin saja bisa jadi" },
  { time: 204.70, text: "Bila kamu datang lagi" },
  { time: 207.90, text: "Ku 'kan terimamu kembali" },
  { time: 215.06, text: "Kalau suatu saat ku cerita burukmu" },
  { time: 218.03, text: "Takkan kutambahkan bumbu apa pun" },
  { time: 221.14, text: "Tak sama seperti saat kuceritakan baikmu" },
  { time: 227.76, text: "Kalau suatu saat ku cerita burukmu" },
  { time: 230.89, text: "Takkan kutambahkan bumbu apa pun" },
  { time: 234.10, text: "Tak sama seperti saat kuceritakan baikmu" },
  { time: 240.46, text: "Kalau suatu saat ku cerita burukmu" },
  { time: 243.64, text: "Takkan kutambahkan bumbu apa pun" },
  { time: 246.79, text: "Tak sama seperti saat kuceritakan baikmu" },
  { time: 253.25, text: "Kalau suatu saat ku cerita burukmu" },
  { time: 256.43, text: "Takkan kutambahkan bumbu apa pun" },
  { time: 259.58, text: "Tak sama seperti saat kuceritakan baikmu" },
  { time: 264.11, text: "Yang sebagian besar tak benar begitu" },
  { time: 272.26, text: "Hu-uh" }
];