var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 13.85, text: "Perjalanan melintasi" },
  { time: 19.86, text: "Kota ini" },
  { time: 26.03, text: "Dua langit, dua hari" },
  { time: 31.18, text: "Kau temani aku di sini" },
  { time: 38.58, text: "Jatuh cinta memang manis" },
  { time: 44.15, text: "Tak mau waktu ini habis" },
  { time: 49.61, text: "Penuhilah hati ini" },
  { time: 54.63, text: "Tak lagi sendiri" },
  { time: 61.44, text: "Oh, dengannya, dengan dia" },
  { time: 66.83, text: "Langkahku sempurna" },
  { time: 73.90, text: "Jatuh cinta memang manis" },
  { time: 79.65, text: "Apalagi ada kamu di sini" },
  { time: 84.84, text: "Genggam tanganku, sayang" },
  { time: 90.54, text: "Kota ini tak sama tanpamu" },
  { time: 96.21, text: "Masih rasa ingin lagi habiskan waktu di sini" },
  { time: 101.94, text: "Mungkin tiga atau empat hari lagi" },
  { time: 114.81, text: "Penuhilah rencanamu" },
  { time: 119.61, text: "Bersamaku lagi" },
  { time: 125.58, text: "Oh, denganmu terasa cepat berlalu" },
  { time: 130.04, text: "Belum puas, ingin lebih tahu jalanan kotamu" },
  { time: 138.98, text: "Jatuh cinta memang manis" },
  { time: 144.81, text: "Apalagi ada kamu di sini" },
  { time: 150.01, text: "Genggam tanganku, sayang" },
  { time: 155.84, text: "Kota ini tak sama tanpamu" },
  { time: 161.20, text: "Masih rasa ingin lagi habiskan waktu di sini" },
  { time: 167.07, text: "Mungkin tiga atau empat hari lagi" },
  { time: 200.80, text: "Genggam tanganku, sayang" },
  { time: 206.40, text: "Kota ini tak sama tanpamu" },
  { time: 211.65, text: "Masih rasa ingin lagi habiskan waktu di sini" },
  { time: 217.36, text: "Mungkin tiga atau empat hari lagi" },
  { time: 225.24, text: "Genggam tanganku, sayang" },
  { time: 229.98, text: "Kota ini tak sama tanpamu" },
  { time: 235.21, text: "Masih rasa ingin lagi habiskan waktu di sini" },
  { time: 241.08, text: "Mungkin tiga atau empat hari lagi" },
  { time: 247.63, text: "Oh-oh-oh" },
  { time: 250.36, text: "Atau mungkin selamanya" },
  { time: 253.29, text: "Rumahku hanyalah kita" },
  { time: 256.12, text: "Kau dan aku sempurna di mana-mana" }
];