var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 26.34, text: "Lihat kebunku" },
  { time: 28.70, text: "Tercipta sempurna" },
  { time: 31.61, text: "Sederhana" },
  { time: 34.45, text: "Satu yang kupunya" },
  { time: 36.85, text: "Setiap hari" },
  { time: 39.65, text: "Kusiram sendiri" },
  { time: 42.33, text: "Wahai melati" },
  { time: 45.00, text: "Kau cantik berseri" },
  { time: 49.10, text: "Sungguh kelabu" },
  { time: 55.12, text: "Kulukis indah rupamu" },
  { time: 60.02, text: "Oh sungguh layu" },
  { time: 65.73, text: "Harapanku kepadamu" },
  { time: 71.93, text: "Oh mengapa" },
  { time: 75.06, text: "Bunga di taman hatiku hanya satu" },
  { time: 82.54, text: "Oh menghilang" },
  { time: 85.66, text: "Bunga kesayanganku diambil orang" },
  { time: 101.25, text: "Mekarlah selamanya di taman yang lain" },
  { time: 107.70, text: "Sungguh kelabu" },
  { time: 112.48, text: "Kini tamanku tanpamu" },
  { time: 117.08, text: "Jangan kau layu" },
  { time: 122.97, text: "Semesta kan menjagamu" },
  { time: 129.01, text: "Oh mengapa" },
  { time: 131.99, text: "Bunga di taman hatiku hanya satu" },
  { time: 139.72, text: "Oh menghilang" },
  { time: 142.77, text: "Bunga kesayanganku tak mengapa" },
  { time: 148.22, text: "Bila di taman hatiku tak berbunga" },
  { time: 155.77, text: "Bersenanglah" },
  { time: 158.96, text: "Bunga kesayanganku tumbuh bahagia" },
  { time: 173.50, text: "Hm-hm-hm-hm-hm-hm" },
  { time: 177.78, text: "Hm-hm-hm-hm-hm-hm" }
];