var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 31, text: "Suatu malam adam bercerita" },
  { time: 42, text: "Hawanya tak lagi di jalur yang sama" },
  { time: 52, text: "Bacaan dan doa yang mulai berbeda" },
  { time: 62, text: "Ego dan air mata kita bicara" },
  { time: 72, text: "Gila tak masuk logika" },
  { time: 80, text: "Termangu hatiku" },
  { time: 87, text: "Kau menggenggam kumenadahnya" },
  { time: 98, text: "Berdamai dengan apa yang terjadi" },
  { time: 108, text: "Kunci dari semua masalah ini" },
  { time: 118, text: "Jujur tak mudah untuk melangkah pergi" },
  { time: 128, text: "Ini soal hati bukan yang diyakini" },
  { time: 137, text: "Ow gila tak masuk logika" },
  { time: 147, text: "Termangu hatiku" },
  { time: 154, text: "Kau menggenggam kumenadahnya" },
  { time: 158, text: "Ow gila ini tak biasa" },
  { time: 167, text: "Tertegun hatiku" },
  { time: 174, text: "Kau menggenggam kumenadahnya" },
  { time: 184, text: "Ho oh" },
  { time: 198, text: "Jangan salahkan faham ku kini tertuju oh" },
  { time: 208, text: "Siapa yang tau" },
  { time: 211, text: "Siapa yang mau" },
  { time: 214, text: "Kau di sana" },
  { time: 215, text: "Aku diseberangmu" },
  { time: 218, text: "Cerita kita sulit dicerna" },
  { time: 224, text: "Tak lagi sama" },
  { time: 226, text: "Cara berdoa" },
  { time: 229, text: "Cerita kita sulit diterka" },
  { time: 234, text: "Tak lagi sama" },
  { time: 236, text: "Arah kiblatnya oh" },
  { time: 239, text: "Cerita kita sulit dicerna" },
  { time: 244, text: "Tak lagi sama" },
  { time: 247, text: "Cara berdoa" },
  { time: 249, text: "Oh cerita kita sulit diterka" },
  { time: 254, text: "Tak lagi sama" },
  { time: 257, text: "Arah kiblatnya" }
]