var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 13.68, text: "Malam yang berat kali ini merindumu lagi" },
  { time: 20.57, text: "Dan masihkah kau mengingat diriku?" },
  { time: 27.34, text: "Takkan apa (jika) kau t'lah lupa (sudah)" },
  { time: 30.13, text: "Dan biarkan masa tiba cerahkan hari" },
  { time: 33.45, text: "Aku sudah (bisa) 'tuk terima (semua)" },
  { time: 37.51, text: "Biar ku sembuh sendiri" },
  { time: 43.97, text: "Tapi andai engkau tahu, sungguh, aku sangat rindu" },
  { time: 50.55, text: "Dan biarkanlah angin sampaikan rinduku (padamu)" },
  { time: 57.81, text: "Dan biarkanlah waktu yang sembuhkan diriku" },
  { time: 63.89, text: "Kar'na takkan ada yang bisa gantikanmu saat ini" },
  { time: 75.30, text: "Malam yang berat kali ini merindumu lagi" },
  { time: 82.38, text: "Dan masihkah kau mengingat diriku?" },
  { time: 88.81, text: "Takkan apa (takkan apa) kau t'lah lupa (kau t'lah lupa)" },
  { time: 92.12, text: "Dan biarkan masa tiba cerahkan hari" },
  { time: 95.44, text: "Aku sudah (sudah) 'tuk terima (terima)" },
  { time: 98.97, text: "Biar ku sembuh sendiri" },
  { time: 103.99, text: "Tapi andai engkau tahu, sungguh, aku sangat rindu (sangat rindu)" },
  { time: 110.61, text: "Dan biarkanlah angin sampaikan rinduku" },
  { time: 117.38, text: "Dan biarkanlah waktu yang sembuhkan diriku" },
  { time: 124.10, text: "Kar'na takkan ada yang bisa gantikanmu saat ini" },
  { time: 159.21, text: "Tapi andai engkau tahu, sungguh, aku sangat rindu" },
  { time: 165.57, text: "Dan biarkanlah angin sampaikan rinduku" },
  { time: 172.60, text: "Dan biarkanlah waktu yang sembuhkan diriku" },
  { time: 179.08, text: "Kar'na takkan ada yang bisa gantikanmu saat ini" },
  { time: 192.45, text: "Sangat rindu" },
  { time: 197.35, text: "(Dan biarkanlah angin sampaikan rinduku)" },
  { time: 200.14, text: "Tapi andai engkau tahu, sungguh, aku sangat rindu" },
  { time: 206.69, text: "Dan biarkanlah angin sampaikan rinduku" }
];