var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 6.72, text: "Hm-mm, hm-mm" },
  { time: 13.49, text: "Bagaikan kemarau yang panjang" },
  { time: 19.72, text: "Kurindukan turunnya hujan" },
  { time: 26.16, text: "Waktu yang berselang menunggumu pulang" },
  { time: 33.25, text: "Kembali mengulang kenangan" },
  { time: 40.02, text: "Masa-masa indah, senyum bahagia" },
  { time: 47.00, text: "Yang mungkin takkan lagi datang" },
  { time: 58.02, text: "Bagaikan sungai yang bercabang" },
  { time: 64.60, text: "Bertemu di laut yang sama" },
  { time: 70.78, text: "Begitu pun juga kita manusia" },
  { time: 77.71, text: "Ada pisah dan pertemuan" },
  { time: 84.49, text: "Tangisan dan tawa, sedih dan bahagia" },
  { time: 91.59, text: "Tak kekal, hanya sementara" },
  { time: 97.33, text: "Usap pelan air mataku" },
  { time: 105.55, text: "Sadari waktu akan berlalu" },
  { time: 112.76, text: "Rindu yang lalu 'kan jadi satu" },
  { time: 120.93, text: "Senyumlah bersamaku, sabarlah menunggu" },
  { time: 127.95, text: "Kita 'kan bertemu di ruang baru" },
  { time: 140.46, text: "Hm-mm-hm, hm-mm-hm" },
  { time: 172.80, text: "Usap pelan air mataku" },
  { time: 180.99, text: "Sadari waktu akan berlalu" },
  { time: 188.13, text: "Rindu yang lalu 'kan jadi satu" },
  { time: 196.41, text: "Senyumlah bersamaku, sabarlah menunggu" },
  { time: 203.31, text: "Kita 'kan bertemu di ruang baru" },
  { time: 210.38, text: "Kita 'kan bertemu di ruang baru" },
  { time: 221.52, text: "Oh-oh-oh, hm-hm" }
];