var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 21.68, text: "Jadi waktu itu dingin" },
  { time: 24.97, text: "Kuberi kau hangat" },
  { time: 27.99, text: "Walaupun ku juga beku" },
  { time: 30.24, text: "Tapi ku aman saat kau nyaman" },
  { time: 34.96, text: "Jadi waktu itu panas" },
  { time: 38.29, text: "Kuberi kau angin" },
  { time: 41.53, text: "Walaupun ku juga gerah" },
  { time: 44.10, text: "Tapi ku penuh saat kau teduh" },
  { time: 47.22, text: "Sudah paham 'kan sejauh ini?" },
  { time: 54.95, text: "Ku yang lama di sini" },
  { time: 57.14, text: "Menjagamu tak patah hati" },
  { time: 60.30, text: "Sedia aku sebelum hujan" },
  { time: 63.76, text: "Apa yang kau butuh, kuberikan" },
  { time: 67.11, text: "Ke mana pun tak akan kau temukan" },
  { time: 70.41, text: "Yang siapkan bekalmu di peperangan" },
  { time: 73.84, text: "Jika tak setara, kumaafkan" },
  { time: 77.21, text: "Memang sebegitunya aku" },
  { time: 88.20, text: "Ku tak punya pilihan" },
  { time: 91.44, text: "Yang dikendali pikiran" },
  { time: 94.79, text: "Ada namamu disebutkan" },
  { time: 97.55, text: "Ke situlah arahku berjalan" },
  { time: 100.52, text: "Sudah paham 'kan sejauh ini?" },
  { time: 108.22, text: "Ku yang lama di sini" },
  { time: 110.46, text: "Menjagamu tak patah hati" },
  { time: 113.69, text: "Sedia aku sebelum hujan" },
  { time: 117.04, text: "Apa yang kau butuh, kuberikan" },
  { time: 120.41, text: "Ke mana pun tak akan kau temukan" },
  { time: 123.72, text: "Yang siapkan bekalmu di peperangan" },
  { time: 127.12, text: "Jika tak setara, kumaafkan" },
  { time: 130.50, text: "Memang sebegitunya aku" },
  { time: 133.90, text: "Soal cinta, aku jatuh, yeah-hey" },
  { time: 140.73, text: "Ini janjiku" },
  { time: 145.93, text: "Untuk hadir dan mencintaimu" },
  { time: 155.68, text: "Di hari baikmu" },
  { time: 158.84, text: "Dan di hari burukmu" },
  { time: 162.34, text: "Sedia aku sebelum hujan" },
  { time: 165.54, text: "Apa yang kau butuh, kuberikan" },
  { time: 170.08, text: "Ku yang lama di sini" },
  { time: 172.20, text: "Menjagamu tak patah hati" },
  { time: 175.28, text: "Sedia aku sebelum hujan" },
  { time: 178.76, text: "Apa yang kau butuh, kuberikan" },
  { time: 182.10, text: "Ke mana pun tak akan kau temukan" },
  { time: 185.39, text: "Yang siapkan bekalmu di peperangan" },
  { time: 190.25, text: "(Jika tak setara) kumaafkan" },
  { time: 192.07, text: "Memang sebegitunya aku" },
  { time: 195.39, text: "Soal cinta, aku jatuh, hey" },
  { time: 206.66, text: "sedia aku sebelum hujan" },
  { time: 212.14, text: "(Yang siapkan bekalmu di peperangan)" },
  { time: 213.50, text: "Sedia aku sebelum hujan" }
];