var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 1.67, text: "Kita usahakan rumah itu" },
  { time: 6.45, text: "Dari depan akan tampak sederhana" },
  { time: 11.46, text: "Tapi kebunnya luas" },
  { time: 14.03, text: "Tanamannya mewah, megah" },
  { time: 21.82, text: "Kita usahakan rumah itu" },
  { time: 26.82, text: "Dari depan akan tampak sederhana" },
  { time: 31.68, text: "Tapi dibuat kuat" },
  { time: 34.51, text: "Dirancang muat, lega" },
  { time: 42.43, text: "Urusan perabotan dan wangi-wangian" },
  { time: 47.31, text: "Kuserahkan pada s'leramu yang lebih maju" },
  { time: 52.48, text: "Tapi tata ruang, aku ikut pertimbangkan" },
  { time: 57.41, text: "Kar'na kalau nanti kita punya kesibukan" },
  { time: 63.04, text: "Malam tetap kumpul di meja panjang" },
  { time: 69.38, text: "Ruang makan kita" },
  { time: 72.59, text: "Berbincang tentang hari yang panjang" },
  { time: 92.57, text: "Kita usahakan rumah itu" },
  { time: 97.34, text: "Dari depan akan tampak sederhana" },
  { time: 102.35, text: "Tapi penerangannya" },
  { time: 104.92, text: "Diracik begitu romantis" },
  { time: 113.08, text: "Urusan perabotan dan wangi-wangian" },
  { time: 118.07, text: "Kuserahkan pada s'leramu yang lebih maju" },
  { time: 123.14, text: "Tapi tata ruang, aku ikut pertimbangkan" },
  { time: 128.28, text: "Kar'na kalau nanti kita punya kesibukan" },
  { time: 133.75, text: "Malam tetap kumpul di meja panjang" },
  { time: 140.11, text: "Ruang makan kita" },
  { time: 142.82, text: "Berbincang tentang hari yang panjang" },
  { time: 153.19, text: "Boleh kamu keliling dunia" },
  { time: 157.47, text: "Dan temukan banyak tempat-tempat 'tuk singgah" },
  { time: 166.99, text: "Sementara" },
  { time: 173.51, text: "Kamu boleh namai itu rumah" },
  { time: 178.17, text: "Selama ada m'reka yang kamu cinta" },
  { time: 187.14, text: "Di dalamnya" }
];