var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 21, text: "Seberapa jauh dari sini" },
  { time: 26, text: "Tembok-tembok ini tak berarti" },
  { time: 31, text: "Asal kulihat senyummu hari ini" },
  { time: 36, text: "Mendengar keluhmu malam nanti" },
  { time: 40, text: "Saat semua tak jelas arahnya" },
  { time: 45, text: "Kita hanya punya bersama" },
  { time: 49, text: "Lewati curam terjalnya dunia" },
  { time: 53, text: "Ramai sepi ini milik bersama" },
  { time: 58, text: "Ramai sepi ini milik bersama" },
  { time: 63, text: "Kita sama-sama takkan ke mana" },
  { time: 67, text: "Selama kau ada aku tak apa" },
  { time: 72, text: "Apa pun yang terjadi tidak apa" },
  { time: 76, text: "Melihat tawa tangis dan isak" },
  { time: 81, text: "Mendengar kabar berbagai macamnya" },
  { time: 86, text: "Kali ini kita belajar banyak" },
  { time: 90, text: "Yang runtuh kita ulangi nantinya" },
  { time: 95, text: "Saat semua tak jelas arahnya" },
  { time: 99, text: "Kita hanya punya bersama" },
  { time: 104, text: "Lewati curam terjalnya dunia" },
  { time: 108, text: "Ramai sepi ini milik bersama" },
  { time: 113, text: "Saat terasa berat-beratnya" },
  { time: 117, text: "Kutahu kau pun berjuang juga" },
  { time: 121, text: "Hadapi semuanya langsung di muka" },
  { time: 127, text: "Apa pun yang terjadi tidak apa" },
  { time: 131, text: "Setiap hari ku bersyukur" },
  { time: 135, text: "Melihatmu" },
  { time: 140, text: "Berselimut harapan" },
  { time: 145, text: "Berbekal cerita" },
  { time: 150, text: "Saat semua tak jelas arahnya" },
  { time: 154, text: "Kita hanya punya bersama" },
  { time: 158, text: "Lewati curam terjalnya dunia" },
  { time: 163, text: "Ramai sepi ini milik bersama" },
  { time: 167, text: "Ramai sepi ini milik bersama." },
  { time: 272, text: "Kita sama-sama takkan ke mana" },
  { time: 277, text: "Selama kau ada aku tak apa" },
  { time: 182, text: "Apa pun yang terjadi tidak apa" }
];