var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 6, text: "Yang kau dengar dalam hati" },
  { time: 14, text: "Biarlah bergema kali ini" },
  { time: 23, text: "Jangan kau redam dan" },
  { time: 25, text: "Yang kau tempa sejauh ini" },
  { time: 33, text: "Jangan kau anggap tak berguna" },
  { time: 42, text: "Hanya kau yang tahu" },
  { time: 44, text: "Semua pengorbananmu" },
  { time: 47, text: "'Tuk hal yang kau cinta" },
  { time: 50, text: "Tanyakan pada dirimu" },
  { time: 56, text: "Sebetapa kau mau" },
  { time: 60, text: "Oh, 'tuk mengubah hidupmu" },
  { time: 64, text: "Di tanganmu, kuasa" },
  { time: 68, text: "Atas ceritamu, sekarang juga" },
  { time: 75, text: "Besok atau hari ini" },
  { time: 79, text: "Kau yang pegang kendali" },
  { time: 83, text: "Di tanganmu, kuasa" },
  { time: 86, text: "Atas ceritamu, sekarang juga" },
  { time: 93, text: "Berbagai cobaan dan hal yang buat kau ragu" },
  { time: 97, text: "Jadikan percikan 'tuk menerpa tekadmu" },
  { time: 102, text: "Jalan hidupmu hanya milikmu sendiri" },
  { time: 107, text: "Rasakan nikmatnya hidupmu hari ini" },
  { time: 112, text: "Berbagai cobaan dan hal yang buat kau ragu" },
  { time: 116, text: "Jadikan percikan 'tuk menerpa tekadmu" },
  { time: 121, text: "Jalan hidupmu hanya milikmu sendiri" },
  { time: 125, text: "Rasakan nikmatnya hidupmu hari ini" },
  { time: 130, text: "Berbagai cobaan dan hal yang buat kau ragu" },
  { time: 135, text: "Jadikan percikan 'tuk menerpa tekadmu" },
  { time: 140, text: "Jalan hidupmu hanya milikmu sendiri" },
  { time: 144, text: "Rasakan nikmatnya hidupmu hari ini" }
];