var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 10, text: "Menyesal tak kusampaikan" },
  { time: 13, text: "Cinta monyetku ke Kanya dan Rebecca" },
  { time: 17, text: "Apa kabar kalian di sana" },
  { time: 21, text: "Semoga hidup baik-baik saja" },
  { time: 26, text: "Tak belajar terkena getahnya" },
  { time: 30, text: "Saat bersama Thanya dan Saphira" },
  { time: 34, text: "Kupercaya mungkin bukan jalannya" },
  { time: 38, text: "Namun kalian banyak salah juga" },
  { time: 42, text: "Jika dahulu ku tak cepat berubah" },
  { time: 47, text: "Ini maafku untukmu Sharfina" },
  { time: 50, text: "Segala doa yang baik adanya" },
  { time: 55, text: "Untukmu dan mimpimu yang mulia" },
  { time: 59, text: "Pindah berkala rumah ke rumah" },
  { time: 64, text: "Berharap bisa berujung indah" },
  { time: 68, text: "Walau akhirnya harus berpisah" },
  { time: 72, text: "Trima kasih karna ku tak mudah" },
  { time: 76, text: "Pindah berkala rumah ke rumah" },
  { time: 80, text: "Berharap bisa berujung indah" },
  { time: 84, text: "Walau akhirnya harus berpisah" },
  { time: 88, text: "Trima kasih karna ku tak mudah" },
  { time: 94, text: "Hm" },
  { time: 100, text: "Maaf jika ku sering buat susah" },
  { time: 104, text: "Indisya Panda Anggra Caca Sismita" },
  { time: 108, text: "Prempuan terkuat dalam hidupku" },
  { time: 112, text: "Terjanglah apa pun yang kalian tuju" },
  { time: 117, text: "Kau datang saat gelapku merekah" },
  { time: 121, text: "Seluruh hatiku untukmu Meidiana" },
  { time: 125, text: "Kau pantas dapatkan yang baik di dunia" },
  { time: 130, text: "Smoga kita bertahan lama" },
  { time: 134, text: "Pindah berkala rumah ke rumah" },
  { time: 138, text: "Mengambil pelajaran jika berpisah" },
  { time: 142, text: "Jikalau suatu saat berujung indah" },
  { time: 146, text: "Catat nama kita dalam sejarah" },
  { time: 150, text: "Pindah berkala rumah ke rumah" },
  { time: 155, text: "Mengambil pelajaran jika berpisah" },
  { time: 159, text: "Jikalau suatu saat berujung indah" },
  { time: 163, text: "Catat nama kita dalam sejarah" },
  { time: 167, text: "Letih mengembara rumah ke rumah" },
  { time: 171, text: "Kadang ku lupa akanmu Amalia" },
  { time: 175, text: "Siap sedia tiap ku bercerita" },
  { time: 179, text: "Ku beruntung jadi anakmu Bunda" },
  { time: 200, text: "Pindah berkala rumah ke rumah" },
  { time: 204, text: "Selalu pada dirimu aku berserah" },
  { time: 208, text: "Jika aku disebut dalam sejarah" },
  { time: 212, text: "Mreka takkan lupa karna siapa" },
  { time: 217, text: "Pindah berkala rumah ke rumah" },
  { time: 221, text: "Selalu pada dirimu aku berserah" },
  { time: 225, text: "Jika aku disebut dalam sejarah" },
  { time: 229, text: "Mreka takkan lupa karna siapa" }
];