var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 25, text: "Di seluruh tempat di seluruh dunia" },
  { time: 28, text: "Dimanapun lagu cinta ini terputar" },
  { time: 31, text: "Aku bergeleng kecil dan tersenyum tipis" },
  { time: 34, text: "Andai lagu ini tertulis olehku" },
  { time: 37, text: "Direkam yang manis diisi bombastis" },
  { time: 40, text: "Ditujukan secara spesifik untukmu" },
  { time: 43, text: "Tentang hal-hal yang hanya kita berdua tahu" },
  { time: 46, text: "Karena semua lagu cinta terdengar sama" },
  { time: 51, text: "Ha ha ha ha ha ha ha" },
  { time: 53, text: "Semua membosankan semua menjemukan" },
  { time: 59, text: "Tak ada yang bisa gambarkan parasmu" },
  { time: 65, text: "Secara sempurna maka kan kucoba" },
  { time: 70, text: "Karena semua yang lain terdengar sama" },
  { time: 87, text: "Terdengar sama" },
  { time: 101, text: "Semua membosankan semua menjemukan" },
  { time: 107, text: "Tak ada yang bisa gambarkan parasmu oh oh" },
  { time: 113, text: "Secara sempurna maka kan kucoba" },
  { time: 118, text: "Karena semua yang lain terdengar sama" },
  { time: 128, text: "Di seluruh tempat di seluruh dunia" },
  { time: 130, text: "Di mana pun lagu cinta ini terputar (terdengar sama)" },
  { time: 133, text: "Ada film di kepalaku yang kuputar" },
  { time: 136, text: "Adegan romantis pemerannya kamu" },
  { time: 139, text: "Di seluruh tempat di seluruh dunia" },
  { time: 142, text: "Di mana pun lagu cinta ini terputar" },
  { time: 145, text: "Ada film di kepalaku yang kuputar" },
  { time: 148, text: "Adegan romantis pemerannya kamu" },
  { time: 152, text: "Semua membosankan semua menjemukan" },
  { time: 158, text: "Tak ada yang bisa gambarkan parasmu" },
  { time: 164, text: "Secara sempurna maka kan kucoba" },
  { time: 169, text: "Karena semua yang lain terdengar sama" },
  { time: 180, text: "Terdengar sama" },
  { time: 186, text: "Terdengar sama" },
  { time: 192, text: "Terdengar sama" }
];