var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 44, text: "I know a place" },
  { time: 54, text: "It's somewhere I go when I need to remember your face" },
  { time: 64, text: "We get married in our heads" },
  { time: 74, text: "Something to do while we try to recall how we met" },
  { time: 84, text: "Do you think I have forgotten?" },
  { time: 88, text: "Do you think I have forgotten?" },
  { time: 94, text: "Do you think I have forgotten about you?" },
  { time: 104, text: "You and I (don't let go), we're alive (don't let go)" },
  { time: 114, text: "With nothing to do, I could lay and just look in your eyes" },
  { time: 124, text: "Wait (don't let go) and pretend (don't let go)" },
  { time: 134, text: "Hold on and hope that we'll find our way back in the end (in the end)" },
  { time: 144, text: "Do you think I have forgotten?" },
  { time: 149, text: "Do you think I have forgotten?" },
  { time: 154, text: "Do you think I have forgotten about you?" },
  { time: 164, text: "Do you think I have forgotten?" },
  { time: 169, text: "Do you think I have forgotten?" },
  { time: 174, text: "Do you think I have forgotten about you?" },
  { time: 184, text: "And there was something 'bout you that now I can't remember" },
  { time: 185, text: "It's the same damn thing that made my heart surrender" },
  { time: 192, text: "And I miss you on a train, I miss you in the morning" },
  { time: 200, text: "I never know what to think about" },
  { time: 204, text: "I think about you (so don't let go)" },
  { time: 210, text: "About you (so don't let go)" },
  { time: 215, text: "Do you think I have forgotten about you? (Don't let go)" },
  { time: 219, text: "About you" },
  { time: 224, text: "About you" },
  { time: 234, text: "Do you think I have forgotten about you? (Don't let go)" }
]