var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 8.17, text: "You walked into the room" },
  { time: 10.93, text: "And now my heart has been stolen" },
  { time: 16.99, text: "You took me back in time to when I was unbroken" },
  { time: 25.00, text: "Now you're all I want" },
  { time: 26.99, text: "And I knew it from the very first moment" },
  { time: 33.56, text: "'Cause a light came on when I heard that song" },
  { time: 37.47, text: "And I want you to sing it again" },
  { time: 43.61, text: "I swear that every word you sing" },
  { time: 47.25, text: "You wrote them for me" },
  { time: 52.49, text: "Like it was a private show" },
  { time: 54.94, text: "I know you never saw me" },
  { time: 60.25, text: "When the lights come on and I'm on my own" },
  { time: 64.30, text: "Will you be there to sing it again?" },
  { time: 70.12, text: "Could I be the one you talk about in all your stories" },
  { time: 78.43, text: "Can I be him?" },
  { time: 81.66, text: "I heard there was someone but I know he don't deserve you" },
  { time: 90.43, text: "If you were mine I'd never let anyone hurt you" },
  { time: 98.04, text: "I wanna dry those tears, kiss those lips" },
  { time: 102.33, text: "It's all that I've been thinking about" },
  { time: 107.10, text: "'Cause a light came on when I heard that song" },
  { time: 110.95, text: "And I want you to sing it again" },
  { time: 117.22, text: "I swear that every word you sing" },
  { time: 120.51, text: "You wrote them for me" },
  { time: 125.60, text: "Like it was a private show" },
  { time: 128.27, text: "I know you never saw me" },
  { time: 133.59, text: "When the lights come on and I'm on my own" },
  { time: 137.44, text: "Will you be there to sing it again?" },
  { time: 143.73, text: "Could I be the one you talk about in all your stories?" },
  { time: 151.98, text: "Can I be the one?" },
  { time: 156.17, text: "Can I be the one?" },
  { time: 160.30, text: "Can I be the one?" },
  { time: 165.66, text: "Oh, can I, can I be him?" },
  { time: 170.30, text: "Won't you sing it again?" },
  { time: 174.06, text: "Oh, when you sing it again" },
  { time: 177.16, text: "Can I be him?" },
  { time: 179.39, text: "Oh sing it again" },
  { time: 182.74, text: "Oh, when you sing it again" },
  { time: 185.90, text: "Can I be him?" },
  { time: 188.18, text: "I swear that every word you sing" },
  { time: 191.54, text: "You wrote them for me" },
  { time: 196.78, text: "Like it was a private show" },
  { time: 199.67, text: "I know you never saw me" },
  { time: 204.81, text: "When the lights come on and I'm on my own" },
  { time: 208.55, text: "Will you be there, will you be there?" },
  { time: 214.44, text: "Can I be the one you talk about in all your stories?" },
  { time: 222.90, text: "Can I be him?" },
  { time: 227.07, text: "Can I be him?" },
  { time: 231.73, text: "Can I be him?" },
  { time: 236.20, text: "Can I be him?" }
];