var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 3, text: "I know that you like me" },
  { time: 6, text: "And it's kinda frightenin'" },
  { time: 9, text: "Standing here waitin', waitin'" },
  { time: 12, text: "And I became hypnotized" },
  { time: 15, text: "By freckles and bright eyes" },
  { time: 18, text: "Tongue tied" },
  { time: 20, text: "But now" },
  { time: 22, text: "You're so far away and I'm down" },
  { time: 26, text: "Feelin' like a face in the crowd" },
  { time: 31, text: "I'm reachin' for you, terrified" },
  { time: 36, text: "'Cause you could be the one that I love" },
  { time: 40, text: "I could be the one that you dream of" },
  { time: 45, text: "Message in a bottle is all I can do" },
  { time: 49, text: "Standin' here, hopin' it gets to you" },
  { time: 53, text: "You could be the one that I keep, and I" },
  { time: 58, text: "Could be the reason you can't sleep at night" },
  { time: 62, text: "Message in a bottle is all I can do" },
  { time: 66, text: "Standin' here, hopin' it gets to you" },
  { time: 70, text: "These days I'm restless" },
  { time: 75, text: "Work days are endless" },
  { time: 77, text: "Look how you've made me, made me" },
  { time: 80, text: "But time moves faster" },
  { time: 83, text: "Replaying your laughter" },
  { time: 86, text: "Disaster" },
  { time: 88, text: "'Cause now" },
  { time: 91, text: "You're so far away and I'm down" },
  { time: 95, text: "Feelin' like a face in the crowd" },
  { time: 100, text: "I'm reachin' for you, terrified" },
  { time: 104, text: "'Cause you could be the one that I love" },
  { time: 109, text: "I could be the one that you dream of" },
  { time: 113, text: "Message in a bottle is all I can do" },
  { time: 118, text: "Standin' here, hopin' it gets to you (it gets to you)" },
  { time: 121, text: "You could be the one that I keep, and I (I)" },
  { time: 126, text: "Could be the reason you can't sleep at night" },
  { time: 130, text: "Message in a bottle is all I can do" },
  { time: 134, text: "Standin' here, hopin' it gets to you" },
  { time: 138, text: "How is it in London? (London)" },
  { time: 143, text: "Where are you while I'm wonderin' (wonderin')" },
  { time: 146, text: "If I'll ever see you again?" },
  { time: 159, text: "You could be the one that I love, mm-mm" },
  { time: 164, text: "And now I'm standin' here, hopin' it gets to you" },
  { time: 169, text: "'Cause you could be the one that I love" },
  { time: 173, text: "I could be the one that you dream of" },
  { time: 178, text: "Message in a bottle is all I can do" },
  { time: 181, text: "Standin' here, hopin' it gets to you (it gets to you)" },
  { time: 186, text: "You could be the one that I keep, and I" },
  { time: 190, text: "Could be the reason you can't sleep at night (you can't sleep at night)" },
  { time: 195, text: "Message in a bottle is all I can do (yeah, yeah)" },
  { time: 198, text: "Standin' here, hopin' it gets to you (yeah, yeah)" },
  { time: 203, text: "You could be the one that I love" },
  { time: 208, text: "(Love)" },
  { time: 210, text: "You could be the one that I love" },
  { time: 213, text: "(Love) my love" },
  { time: 214, text: "And now I'm standin' here, hopin' this gets to you" }
]