var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 16.90, text: "Cause you're a sky, 'cause you're a sky full of stars" },
  { time: 24.44, text: "I'm gonna give you my heart" },
  { time: 32.29, text: "'Cause you're a sky, 'cause you're a sky full of stars" },
  { time: 40.15, text: "'Cause you light up the path" },
  { time: 47.57, text: "I don't care, go on and tear me apart" },
  { time: 55.23, text: "I don't care if you do, ooh-ooh, ooh" },
  { time: 62.88, text: "'Cause in a sky, 'cause in a sky full of stars" },
  { time: 68.03, text: "I think I saw you" },
  { time: 101.45, text: "'Cause you're a sky, 'cause you're a sky full of stars" },
  { time: 108.89, text: "I wanna die in your arms, oh, oh-oh" },
  { time: 116.86, text: "'Cause you get lighter the more it gets dark" },
  { time: 124.27, text: "I'm gonna give you my heart, oh" },
  { time: 132.15, text: "I don't care, go on and tear me apart" },
  { time: 139.60, text: "I don't care if you do, ooh-ooh, ooh" },
  { time: 147.61, text: "'Cause in a sky, 'cause in a sky full of stars" },
  { time: 152.69, text: "I think I see you" },
  { time: 160.58, text: "I think I see you" },
  { time: 216.62, text: "'Cause you're a sky, you're a sky full of stars" },
  { time: 221.81, text: "Such a heavenly view" },
  { time: 224.24, text: "You're such a heavenly view" },
  { time: 232.96, text: "Yeah, yeah, yeah, ooh" }
];