var lyrics = [
  { time: 3.02, text: "Ooh" },
  { time: 8.68, text: "I, I just woke up from a dream" },
  { time: 15.15, text: "Where you and I had to say goodbye" },
  { time: 19.97, text: "And I don't know what it all means" },
  { time: 24.20, text: "But since I survived, I realized" },
  { time: 28.80, text: "Wherever you go, that's where I'll follow" },
  { time: 33.48, text: "Nobody's promised tomorrow" },
  { time: 37.86, text: "So I'ma love you every night like it's the last night" },
  { time: 41.97, text: "Like it's the last night" },
  { time: 44.00, text: "If the world was ending, I'd wanna be next to you" },
  { time: 53.68, text: "If the party was over and our time on Earth was through" },
  { time: 62.24, text: "I'd wanna hold you just for a while and die with a smile" },
  { time: 71.82, text: "If the world was ending, I'd wanna be next to you" },
  { time: 80.91, text: "Ooh" },
  { time: 84.97, text: "Ooh, lost, lost in the words that we scream" },
  { time: 92.64, text: "I don't even wanna do this anymore" },
  { time: 97.48, text: "'Cause you already know what you mean to me" },
  { time: 100.84, text: "And our love's the only war worth fighting for" },
  { time: 106.60, text: "Wherever you go, that's where I'll follow" },
  { time: 110.92, text: "Nobody's promised tomorrow" },
  { time: 115.26, text: "So I'ma love you every night like it's the last night" },
  { time: 119.30, text: "Like it's the last night" },
  { time: 121.52, text: "If the world was ending, I'd wanna be next to you" },
  { time: 131.07, text: "If the party was over and our time on Earth was through" },
  { time: 139.97, text: "I'd wanna hold you just for a while and die with a smile" },
  { time: 149.11, text: "If the world was ending, I'd wanna be next to you" },
  { time: 158.07, text: "Right next to you" },
  { time: 162.70, text: "Next to you" },
  { time: 167.17, text: "Right next to you" },
  { time: 170.90, text: "Oh-oh, oh" },
  { time: 190.27, text: "If the world was ending, I'd wanna be next to you" },
  { time: 199.33, text: "If the party was over and our time on Earth was through" },
  { time: 208.17, text: "I'd wanna hold you just for a while and die with a smile" },
  { time: 217.61, text: "If the world was ending, I'd wanna be next to you" },
  { time: 226.51, text: "If the world was ending, I'd wanna be next to you" },
  { time: 235.70, text: "Ooh" },
  { time: 238.86, text: "I'd wanna be next to you" }
];