var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 8, text: "Sweet disposition" },
  { time: 23, text: "Never too soon" },
  { time: 38, text: "Oh, reckless abandon" },
  { time: 52, text: "Like no one's watching you" },
  { time: 67, text: "A moment, a love" },
  { time: 70, text: "A dream, aloud" },
  { time: 71, text: "A kiss, a cry" },
  { time: 73, text: "Our rights, our wrongs" },
  { time: 74, text: "A moment, a love" },
  { time: 77, text: "A dream, aloud" },
  { time: 79, text: "A moment, a love" },
  { time: 80, text: "A dream, aloud" },
  { time: 82, text: "Just stay there" },
  { time: 88, text: "'Cause I'll be coming over" },
  { time: 95, text: "And while our blood's still young" },
  { time: 99, text: "It's so young, it runs" },
  { time: 103, text: "And won't stop 'til it's over" },
  { time: 110, text: "Won't stop to surrender" },
  { time: 119, text: "Songs of desperation" },
  { time: 134, text: "I played them for you" },
  { time: 149, text: "A moment, a love" },
  { time: 151, text: "A dream, aloud" },
  { time: 153, text: "A kiss, a cry" },
  { time: 154, text: "Our rights, our wrongs" },
  { time: 160, text: "A moment, a love" },
  { time: 160, text: "A dream, aloud" },
  { time: 161, text: "A moment, a love" },
  { time: 165, text: "A dream, aloud" },
  { time: 166, text: "Stay there" },
  { time: 169, text: "'Cause I'll be coming over" },
  { time: 170, text: "And while our blood's still young" },
  { time: 180, text: "It's so young, it runs" },
  { time: 183, text: "Won't stop 'til it's over" },
  { time: 191, text: "Won't stop to surrender" },
  { time: 199, text: "Won't stop 'til it's over" },
  { time: 206, text: "Won't stop 'til it's over" },
  { time: 213, text: "Won't stop 'til it's over" },
  { time: 224, text: "Won't stop to surrender" }
]