var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 22, text: "Touch my body tender" },
  { time: 27, text: "'Cause the feeling makes me weak" },
  { time: 33, text: "Kicking off the covers" },
  { time: 37, text: "I see the ceiling while you're looking down at me" },
  { time: 43, text: "How can we go back to being friends" },
  { time: 48, text: "When we just shared a bed?" },
  { time: 54, text: "How can you look at me and pretend" },
  { time: 58, text: "I'm someone you've never met?" },
  { time: 64, text: "It was last December" },
  { time: 68, text: "You were layin' on my chest" },
  { time: 74, text: "I still remember" },
  { time: 78, text: "I was scared to take a breath, didn't want you to move your head" },
  { time: 85, text: "How can we go back to being friends" },
  { time: 89, text: "When we just shared a bed? (Yeah)" },
  { time: 95, text: "How can you look at me and pretend" },
  { time: 100, text: "I'm someone you've never met?" },
  { time: 105, text: "The devil in your eyes" },
  { time: 112, text: "Won't deny the lies" },
  { time: 115, text: "You've sold, I'm holding on too tight" },
  { time: 122, text: "While you let go, this is casual" },
  { time: 136, text: "How can we go back to being friends" },
  { time: 141, text: "When we just shared a bed? (Yeah)" },
  { time: 147, text: "How can you look at me and pretend" },
  { time: 151, text: "I'm someone you've never met?" },
  { time: 156, text: "How can we go back to being friends" },
  { time: 162, text: "When we just shared a bed? (Yeah)" },
  { time: 168, text: "How can you look at me and pretend" },
  { time: 172, text: "I'm someone you've never met?" },
  { time: 180, text: "I'm someone you've never met" },
  { time: 187, text: "Oh yeah" }
];