var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 10, text: "How are you in your time alone?" },
  { time: 14, text: "I'm doing fine" },
  { time: 16, text: "Well, I'm not" },
  { time: 17, text: "I feel like I wanna die" },
  { time: 21, text: "I have so much to tell you, love" },
  { time: 26, text: "From the start of the day 'til the dawn breaks away" },
  { time: 31, text: "I've been thinking of you" },
  { time: 35, text: "And I've been missing your voice on the other side" },
  { time: 42, text: "And I've been dreaming of you" },
  { time: 46, text: "And I can hear you singing through the Silent Night" },
  { time: 53, text: "Do you ever feel the need to get away from me?" },
  { time: 59, text: "Do I bore you?" },
  { time: 61, text: "Or do you want to take me from this crowded place to" },
  { time: 67, text: "Somewhere we can find some peace" },
  { time: 70, text: "And the world is ours to keep" },
  { time: 80, text: "Hm" },
  { time: 84, text: "They don't have to know how we touch" },
  { time: 88, text: "'Cause this feeling's all ours" },
  { time: 92, text: "They'd become so loud trying to" },
  { time: 96, text: "Fix what was never really broken" },
  { time: 99, text: "And you are my safe haven" },
  { time: 102, text: "I am on your side" },
  { time: 106, text: "Do you ever feel the need to get away from me?" },
  { time: 112, text: "Do I bore you?" },
  { time: 115, text: "Or do you want to take me from this crowded place to" },
  { time: 121, text: "Somewhere we can find some peace" },
  { time: 124, text: "And the world is ours to keep" },
  { time: 133, text: "Hm" },
  { time: 137, text: "In this world, we are fading away" },
  { time: 142, text: "And I'm not fine" },
  { time: 143, text: "Sometimes, it gets so lonely" },
  { time: 145, text: "But I'm still scared to ask for help" },
  { time: 149, text: "But I'll look at you the same as today" },
  { time: 153, text: "The one that I've been needing" },
  { time: 155, text: "I never thought I'd have" },
  { time: 159, text: "I've been thinking of you" },
  { time: 163, text: "And I've been missing your voice on the other side" },
  { time: 170, text: "Do you ever feel the need to get away from me?" },
  { time: 176, text: "Do I bore you?" },
  { time: 179, text: "Or do you want to take me from this crowded place to" },
  { time: 185, text: "Somewhere we can find some peace" },
  { time: 188, text: "And the world is ours to keep" }
];