var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 5.88, text: "I'm packin' my bags that I didn't unpack the last time" },
  { time: 11.90, text: "I'm sayin', "See you again, " so many times, it's becoming my tagline" },
  { time: 18.48, text: "But you know the truth, I'd rather hold you" },
  { time: 21.61, text: "Than try to catch this flight" },
  { time: 25.07, text: "So many things I'd rather say" },
  { time: 27.26, text: "But for now, it's goodbye" },
  { time: 31.31, text: "You say I'm always leavin'" },
  { time: 37.95, text: "You, when you're sleepin' alone" },
  { time: 43.00, text: "But the, the car's outside" },
  { time: 46.31, text: "But I don't wanna go tonight" },
  { time: 50.96, text: "I'm not gettin' in the Addison Lee" },
  { time: 56.06, text: "Unless you pack your bags" },
  { time: 59.83, text: "You're comin' with me" },
  { time: 64.55, text: "I'm tired of lovin' from afar" },
  { time: 67.84, text: "And never being where you are" },
  { time: 71.25, text: "Close the windows, lock the doors" },
  { time: 74.21, text: "Don't wanna leave you anymore" },
  { time: 79.16, text: "Oh-oh, ah" },
  { time: 82.73, text: "I'm starin' at the same four walls in a different hotel" },
  { time: 89.08, text: "It's an unfamiliar feelin' but I know it so well" },
  { time: 94.65, text: "Oh, but you know the truth, I'd rather hold you" },
  { time: 98.37, text: "Than this mobile in my hand" },
  { time: 101.84, text: "But I guess it'll do, 'cause for you" },
  { time: 104.18, text: "I would run up my phone bill" },
  { time: 108.23, text: "You say I'm always leavin'" },
  { time: 114.61, text: "You, when you need me the most" },
  { time: 119.79, text: "But the, the car's outside" },
  { time: 122.94, text: "But I don't wanna go tonight" },
  { time: 127.47, text: "I'm not gettin' in the Addison Lee" },
  { time: 132.85, text: "Unless you pack your bags" },
  { time: 136.72, text: "You're comin' with me" },
  { time: 141.36, text: "I'm tired of lovin' from afar" },
  { time: 144.60, text: "And never being where you are" },
  { time: 147.91, text: "Close the windows, lock the doors" },
  { time: 151.05, text: "Don't wanna leave you anymore" },
  { time: 153.93, text: "Ooh-ooh, ah" },
  { time: 157.08, text: "Ooh-ooh, ah" },
  { time: 160.30, text: "Ooh-ooh, ah" },
  { time: 163.81, text: "Don't wanna leave you anymore" },
  { time: 166.96, text: "Oh, darling, all of the city lights" },
  { time: 169.98, text: "Never shine as bright as your eyes" },
  { time: 173.42, text: "I would trade them all for a minute more" },
  { time: 176.70, text: "But the car's outside" },
  { time: 178.78, text: "And he's called me twice" },
  { time: 182.00, text: "But he's gonna have to wait tonight" },
  { time: 185.14, text: "I'm not gettin' in the Addison Lee" },
  { time: 190.54, text: "Unless you pack your bags" },
  { time: 194.28, text: "You're comin' with me" },
  { time: 199.16, text: "I'm tired of lovin' from afar" },
  { time: 202.22, text: "And never being where you are" },
  { time: 205.58, text: "Close the windows, lock the doors" },
  { time: 208.58, text: "Don't wanna leave you anymore" },
  { time: 211.63, text: "Ooh-ooh, ah" },
  { time: 214.78, text: "Ooh-ooh, ah" },
  { time: 217.97, text: "Ooh-ooh, ah" },
  { time: 221.74, text: "No, I don't wanna leave you anymore" },
  { time: 225.81, text: "I don't wanna leave you" },
  { time: 224.87, text: "(Ooh-ooh, ah) I don't wanna leave you" },
  { time: 227.90, text: "(Ooh-ooh, ah) I don't wanna leave you" },
  { time: 234.51, text: "Don't wanna leave you anymore" }
];