var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 25, text: "I saw her in the rightest way" },
  { time: 29, text: "Looking like Anne Hathaway" },
  { time: 34, text: "Laughing while she hit her pen" },
  { time: 39, text: "And coughed, and coughed" },
  { time: 44, text: "And then, she came up to my knees" },
  { time: 49, text: "Begging, \"Baby, would you please?" },
  { time: 55, text: "Do the things you said you'd do to me, to me?\"" },
  { time: 63, text: "Oh, won't you kiss me on the mouth and love me like a sailor?" },
  { time: 70, text: "And when you get a taste, can you tell me what's my flavor?" },
  { time: 75, text: "I don't believe in God, but I believe that you're my savior" },
  { time: 80, text: "My mom says that she's worried, but I'm covered in His favor" },
  { time: 85, text: "And when we're getting dirty, I forget all that is wrong" },
  { time: 90, text: "I sleep so I can see you 'cause I hate to wait so long" },
  { time: 95, text: "I sleep so I can see you and I hate to wait so long" },
  { time: 105, text: "She took my fingers to her mouth" },
  { time: 110, text: "The kind of thing that makes you proud" },
  { time: 115, text: "That nothing else had ever" },
  { time: 120, text: "Worked out, worked out" },
  { time: 125, text: "And maybe I tried other things" },
  { time: 130, text: "But nothing can capture the sting" },
  { time: 135, text: "Of the venom she's gonna spit out right now" },
  { time: 145, text: "Oh, won't you kiss me on the mouth and love me like a sailor?" },
  { time: 150, text: "When you get a taste, can you tell me what's my flavor?" },
  { time: 155, text: "I don't believe in God, but I believe that you're my savior" },
  { time: 161, text: "I know that you've been worried, but you're dripping in my favor" },
  { time: 165, text: "And when we're getting dirty, I forget all that is wrong" },
  { time: 170, text: "I sleep so I can see you 'cause I hate to wait so long" },
  { time: 175, text: "I sleep so that I can see you and I hate to wait so long" },
  { time: 186, text: "And we can run away to the walls inside your house" },
  { time: 191, text: "I can be the cat, baby, you can be the mouse" },
  { time: 196, text: "And we can laugh off things that we know nothing about" },
  { time: 201, text: "We can go forever until you wanna sit it out" }
]