var lyrics = [
  { time: 0, text: "[Intro Instrumental]" },
  { time: 3, text: "Remember when we would stay out too late" },
  { time: 8, text: "We were young, having fun, made mistakes" },
  { time: 10, text: "Did we ever know?" },
  { time: 12, text: "Did we ever know?" },
  { time: 14, text: "Did we ever know? Yeah..." },
  { time: 19, text: "All the things we'd just think of and say" },
  { time: 23, text: "Never wrong, always right, not afraid" },
  { time: 26, text: "Did we ever know?" },
  { time: 28, text: "Did we ever know?" },
  { time: 30, text: "Did we ever know?" },
  { time: 34, text: "Is it all inside of my head?" },
  { time: 37, text: "Maybe you still think I don't care" },
  { time: 42, text: "But all I need is you" },
  { time: 44, text: "Yeah, you know it's true" },
  { time: 46, text: "Yeah, you know it's true" },
  { time: 48, text: "Forget about where we are" },
  { time: 52, text: "And let go, we're so close" },
  { time: 56, text: "If you don't know where to start" },
  { time: 60, text: "Just hold on and don't run" },
  { time: 64, text: "No..." },
  { time: 65, text: "We're looking back" },
  { time: 67, text: "We're messing around" },
  { time: 69, text: "But that was then" },
  { time: 71, text: "And this is now" },
  { time: 72, text: "All we need is enough love" },
  { time: 77, text: "To hold us" },
  { time: 79, text: "Where we are" },
  { time: 82, text: "Summer days, rushing by you and me" },
  { time: 86, text: "Makes it harder to see underneath" },
  { time: 89, text: "Did we ever know?" },
  { time: 91, text: "Did we ever know?" },
  { time: 93, text: "Did we ever know?" },
  { time: 97, text: "Is it all inside of my head?" },
  { time: 101, text: "Maybe you still think I don't care" },
  { time: 105, text: "But all I need is you" },
  { time: 108, text: "Yeah, you know it's true" },
  { time: 110, text: "Yeah, you know it's true" },
  { time: 112, text: "Forget about where we are" },
  { time: 115, text: "And let go, we're so close" },
  { time: 119, text: "If you don't know where to start" },
  { time: 123, text: "Just hold on and don't run" },
  { time: 128, text: "No..." },
  { time: 129, text: "We're looking back" },
  { time: 131, text: "We're messing around" },
  { time: 133, text: "But that was then" },
  { time: 135, text: "And this is now" },
  { time: 136, text: "All we need is enough love" },
  { time: 140, text: "To hold us" },
  { time: 143, text: "Where we are" },
  { time: 144, text: "But that was then" },
  { time: 150, text: "And this is now" },
  { time: 150, text: "All we need is enough love" },
  { time: 156, text: "To hold us" },
  { time: 159, text: "Where we are..." },
  { time: 167, text: "With closed eyes and open mind" },
  { time: 172, text: "We can be there" },
  { time: 173, text: "We can be there" },
  { time: 175, text: "But this time" },
  { time: 177, text: "Let's cross the line" },
  { time: 179, text: "Can you see it?" },
  { time: 181, text: "Can you see it?" },
  { time: 183, text: "Forget about where we are" },
  { time: 187, text: "And let go, we're so close" },
  { time: 188, text: "If you don't know where to start" },
  { time: 190, text: "Just hold on and don't run" },
  { time: 195, text: "No..." },
  { time: 200, text: "We're looking back" },
  { time: 202, text: "We're messing around" },
  { time: 204, text: "But that was then" },
  { time: 206, text: "And this is now" },
  { time: 207, text: "All we need is enough love" },
  { time: 211, text: "To hold us" },
  { time: 214, text: "Where we are" }
]